// <auto-generated />
using System;
using BrightAcademyApp.Data.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrightAcademyApp.Data.Migrations
{
    [DbContext(typeof(BrightAcademyAppDbContext))]
    [Migration("20230914044009_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("BrightAcademyApp.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Web Geliştirme Kategorisi",
                            IsActive = true,
                            Name = "Web Geliştirme ",
                            Url = "web-gelistirme"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mobil Geliştirme Kategorisi",
                            IsActive = true,
                            Name = "Mobil Geliştirme ",
                            Url = "mobil-gelistirme"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Oyun Geliştirme Kategorisi",
                            IsActive = true,
                            Name = "Oyun Geliştirme ",
                            Url = "oyun-gelistirme"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Siber Güvenlik Kategorisi",
                            IsActive = true,
                            Name = "Siber Güvenlik ",
                            Url = "siber-guvenlik"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Veritabanı Kategorisi",
                            IsActive = true,
                            Name = "Veritabanı  ",
                            Url = "veritabani"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Temel Programlama Kategorisi",
                            IsActive = true,
                            Name = "Temel Programlama  ",
                            Url = "temel-programla"
                        });
                });

            modelBuilder.Entity("BrightAcademyApp.Entity.Concrete.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationEvaluation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EducationFinishTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationGains")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EducationStartTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EducationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EducationTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EducationTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseHours = 600,
                            Description = "Full stack developer olarak çalışan uzmanlar, yazılımların back-end (arka katman) ve front-end(ön katman) olarak nitelendirilen bölümlerinde rol almaktadırlar.",
                            EducationEvaluation = "Web kariyeri açısından çok faydalı bir eğitim.",
                            EducationFinishTime = new DateTime(2023, 9, 14, 7, 40, 9, 51, DateTimeKind.Local).AddTicks(990),
                            EducationGains = "Bu eğitim sayesinde; Temel ve ileri veritabanı mantığını,· Web’in ve yazılımın çalışma prensibini ve tüm süreçlerini,· Yeni nesil tüm programlama araç ve dillerini,· Back end programlamayı ve API yazmayı,· Uçtan uca bir proje geliştirmeyi öğreneceksiniz",
                            EducationLevel = "Medium",
                            EducationStartTime = new DateTime(2023, 9, 14, 7, 40, 9, 51, DateTimeKind.Local).AddTicks(935),
                            EducationStatus = true,
                            EducationTime = 6,
                            EducationTitle = "Temel Programlama : • C# ile Programlama• Değişkenler• Veri Tipleri, Tip Dönüşümleri• Hata Kontrolü, Özel Fonksiyonlar• Döngüler, Koşullu İfadeler• Diziler",
                            EducationType = "Sınıf",
                            ImageUrl = "full-stack-programlama.jpg",
                            IsActive = true,
                            Name = "Full Stack Programlama",
                            Price = 45000m,
                            Url = "full-stack-programlama"
                        },
                        new
                        {
                            Id = 2,
                            CourseHours = 80,
                            Description = "Katılımcıların C# programlama dilini kullanarak farklı platformlarda uygulama geliştirebilecek eğitimlere katılma yeterliliğini elde etmelerini sağlamaktır.",
                            EducationEvaluation = "Temel Programlama açısından çok faydalı bir eğitim.",
                            EducationFinishTime = new DateTime(2023, 9, 14, 7, 40, 9, 51, DateTimeKind.Local).AddTicks(1010),
                            EducationGains = "Bu eğitim sayesinde; Herhangi bir programlama bilgi ve becerisine sahip olmayan her kişinin  C# programlama dilinin en temel özelliklerini kolaylıkla öğrenebileceği başlangıç seviyesinde bir eğitimdir. Bu eğitimle C# programlama dilinin en temel özellikleri öğretilecektir.",
                            EducationLevel = "Easy",
                            EducationStartTime = new DateTime(2023, 9, 14, 7, 40, 9, 51, DateTimeKind.Local).AddTicks(1009),
                            EducationStatus = true,
                            EducationTime = 2,
                            EducationTitle = "Temel Programlama: Değişkenler,Koşullar,Döngüler,Diziler, Visual Studio Code",
                            EducationType = "Online",
                            ImageUrl = "c-sharp.jpg",
                            IsActive = true,
                            Name = "C# Programlama",
                            Price = 15000m,
                            Url = "csharp-programlama"
                        },
                        new
                        {
                            Id = 3,
                            CourseHours = 180,
                            Description = "Bu eğitimin amacı, Java programlama dilini bilenlerin sektörde en yaygın kullanılan teknolojilere adaptasyonunu sağlamaktır.",
                            EducationEvaluation = "Web kariyeri açısından çok faydalı bir eğitim.",
                            EducationFinishTime = new DateTime(2023, 9, 14, 7, 40, 9, 51, DateTimeKind.Local).AddTicks(1013),
                            EducationGains = "Java'yı gerçek projelerde kullanıldığı gibi sıfırdan öğrenecek,Java ile Nesne Yönelimli Programlama (OOP) yapabilecek,SOLID yazılım geliştirme prensiplerini öğrenecek,Tasarım Desenlerine (Design Patterns) giriş yapacak,Sektörde en çok kullanılan Java teknolojilerini öğrenecek.",
                            EducationLevel = "Senior",
                            EducationStartTime = new DateTime(2023, 9, 14, 7, 40, 9, 51, DateTimeKind.Local).AddTicks(1013),
                            EducationStatus = true,
                            EducationTime = 4,
                            EducationTitle = "Spring Boot, Maven, Spring Rest servisi ile backend",
                            EducationType = "Sınıf",
                            ImageUrl = "java.jpg",
                            IsActive = true,
                            Name = "Java",
                            Price = 35000m,
                            Url = "java"
                        },
                        new
                        {
                            Id = 4,
                            CourseHours = 120,
                            Description = "Bu eğitim; React Native ile HTML, CSS ve JavaScript dillerini kullanımını, Visual Studio Code ortamında, Android ve iOS işletim sistemleri için mobil uygulama geliştirmenin detaylarını kapsamaktadır..",
                            EducationEvaluation = "Mobile alanda çalışmak adına çok faydalı bir eğitim.",
                            EducationFinishTime = new DateTime(2023, 9, 14, 7, 40, 9, 51, DateTimeKind.Local).AddTicks(1015),
                            EducationGains = "Bu eğitim sayesinde; Mobil programlamaya dair herşeyi öğreneceksiniz",
                            EducationLevel = "Medium",
                            EducationStartTime = new DateTime(2023, 9, 14, 7, 40, 9, 51, DateTimeKind.Local).AddTicks(1015),
                            EducationStatus = true,
                            EducationTime = 3,
                            EducationTitle = "HTML,CSS,JavaScript,Proje Oluşturma,Component Nedir? Cihaz Yönetimi Web Servis Kullanımı Push Notification Mobil Project Development Market",
                            EducationType = "Online",
                            ImageUrl = "react-native.jpg",
                            IsActive = true,
                            Name = "React Native",
                            Price = 0m,
                            Url = "react-native"
                        },
                        new
                        {
                            Id = 5,
                            CourseHours = 80,
                            Description = "Bu eğitimin amacı Flutter ile Mobil Geliştirmeyi sıfırdan ileri seviyeye gelecek şekilde öğretmektir.",
                            EducationEvaluation = "Mobile alanda çalışmak adına çok faydalı bir eğitim.",
                            EducationFinishTime = new DateTime(2023, 9, 14, 7, 40, 9, 51, DateTimeKind.Local).AddTicks(1026),
                            EducationGains = "Bu eğitim sayesinde; Mobil programlamaya dair herşeyi öğreneceksiniz",
                            EducationLevel = "Medium",
                            EducationStartTime = new DateTime(2023, 9, 14, 7, 40, 9, 51, DateTimeKind.Local).AddTicks(1026),
                            EducationStatus = true,
                            EducationTime = 2,
                            EducationTitle = "HTML,CSS,JavaScript,Proje Oluşturma,Component Nedir? Cihaz Yönetimi Web Servis Kullanımı Push Notification Mobil Project Development Market",
                            EducationType = "Online",
                            ImageUrl = "flutter.jpg",
                            IsActive = true,
                            Name = "Flutter",
                            Price = 0m,
                            Url = "flutter"
                        },
                        new
                        {
                            Id = 6,
                            CourseHours = 80,
                            Description = "Katılımcıların 3 boyutlu Unity uzayına hakimiyet sağlayarak seviye tasarımları geliştirecek bilgi birikimine ulaşmaları ve C# programlama dili yardımı ile bu görsel süreçleri çalışır bir yapı haline dönüştürmelerini sağlamaktır.",
                            EducationEvaluation = "Oyun geliştirme sürecine hâkim olmak isteyenler için çok faydalı bir eğitim.",
                            EducationFinishTime = new DateTime(2023, 9, 14, 7, 40, 9, 51, DateTimeKind.Local).AddTicks(1028),
                            EducationGains = "Unity oyun motoru ile oyun geliştirebilir,3 boyutlu seviye tasarımları oluşturabilir,C# programlama dili ile programlama yapabilir.",
                            EducationLevel = "Medium",
                            EducationStartTime = new DateTime(2023, 9, 14, 7, 40, 9, 51, DateTimeKind.Local).AddTicks(1028),
                            EducationStatus = true,
                            EducationTime = 2,
                            EducationTitle = "Eğitimimize önce 3 boyutlu Unity uzayına hakimiyet sağlayarak başlayacağız, daha sonrasında çevre tasarımları geliştirecek ardından ise programlama tarafına odaklanacağız. Bu alanda yaptığımız çalışmaları tamamladıktan sonra ise üç ayrı oyun örneği ile öğrendiklerimizi uygulamaya geçireceğiz",
                            EducationType = "Online",
                            ImageUrl = "unity.jpg",
                            IsActive = true,
                            Name = "Unity ile 3D Oyun Geliştirme",
                            Price = 0m,
                            Url = "unity-ile-3d-oyun-gelistirme"
                        },
                        new
                        {
                            Id = 7,
                            CourseHours = 120,
                            Description = "Bu eğitimin amacı çeşitli Python kütüphanelerini kullanarak farklı araçların Python ile nasıl entegre edilebileceğini öğrenip, Python ile siber güvenlik kapsamında kullanılabilecek uygulamalar geliştirebilmesini sağlamaktır.",
                            EducationEvaluation = "Siber güvenlik alanına ilgi kişiler,Siber güvenlik kapsamında kendi aracını geliştirmek isteyenler için güzel bir eğitim,",
                            EducationFinishTime = new DateTime(2023, 9, 14, 7, 40, 9, 51, DateTimeKind.Local).AddTicks(1030),
                            EducationGains = " Siber güvenlik için Python ile araç geliştirebilir. Farklı uygulamaları Python ile otomatize edebilir. Web kazıma yapabilir..",
                            EducationLevel = "Sen,or",
                            EducationStartTime = new DateTime(2023, 9, 14, 7, 40, 9, 51, DateTimeKind.Local).AddTicks(1030),
                            EducationStatus = true,
                            EducationTime = 4,
                            EducationTitle = "Bu eğitimde ilk olarak Python programlamaya giriş yapılacak ve çeşitli Python kütüphaneleri kullanılacak sonrasında Socket programlama ile ağ sızma ve web kazıma öğretilecektir.",
                            EducationType = "Sınıf",
                            ImageUrl = "python.jpg",
                            IsActive = true,
                            Name = "Python ile Siber Güvenlik Uygulamaları",
                            Price = 0m,
                            Url = "python-ile-siber-guvenlik-uygulamalari"
                        },
                        new
                        {
                            Id = 8,
                            CourseHours = 80,
                            Description = "Oracle veritabanı ile ilgili, kurulum ve konfigurasyonlar adım adım anlatılacak ve Oracle Veritabanı Mimarisi, Oracle Networking gibi Veritabanı Yöneticiliği Temel Bilgiler örneklendirilecektir.",
                            EducationEvaluation = "Günümüzde Veri Bilimi, Makine Öğrenmesi, Yapay Zekâ, Büyük Veri gibi kavramlar oldukça popüler. Bu kavram ve teknolojileri besleyen asıl yapı verinin kendisidir.",
                            EducationFinishTime = new DateTime(2023, 9, 14, 7, 40, 9, 51, DateTimeKind.Local).AddTicks(1032),
                            EducationGains = "Oracle Veritabanı Mimarisi ve Temel Bilgiler konularına hakim olur,.",
                            EducationLevel = "Medium",
                            EducationStartTime = new DateTime(2023, 9, 14, 7, 40, 9, 51, DateTimeKind.Local).AddTicks(1032),
                            EducationStatus = true,
                            EducationTime = 2,
                            EducationTitle = "Kurs tamamlandığında kariyerine Oracle Veritabanı Yöneticisi olarak devam etmek isteyen herkes ilgili alanlarda çalışabilecek temel bilgi ve beceri edinebilecektir.",
                            EducationType = "Online",
                            ImageUrl = "oracle.jpg",
                            IsActive = true,
                            Name = "Oracle Veritabanı",
                            Price = 0m,
                            Url = "oracle-veritabani"
                        },
                        new
                        {
                            Id = 9,
                            CourseHours = 80,
                            Description = "Veritabanı sistemleri ve ilişkisel veritabanlarını sorgulama dili olan SQL dilinin daha da derinlere inerek T-SQL'i öğretmek. T-SQL sorguları oluşturma, veri türleriyle çalışma, verileri toplama işlevlerini kullanma ve hata işleme konusunda uygulamalı deneyim kazanılmasını sağlamak.",
                            EducationEvaluation = "Günümüzde Veri Bilimi, Makine Öğrenmesi, Yapay Zekâ, Büyük Veri gibi kavramlar oldukça popüler. Bu kavram ve teknolojileri besleyen asıl yapı verinin kendisidir.",
                            EducationFinishTime = new DateTime(2023, 9, 14, 7, 40, 9, 51, DateTimeKind.Local).AddTicks(1034),
                            EducationGains = "TSQL kullaranarak SQL Server üzerinde ileri seviye kodlama yapabilir,TSQL fonksiyonlarını kullanmayı öğrenir.Veribilimi projelerinin gerek şartı olan veri önişleme işlemlerini gerçekleştirebilir.",
                            EducationLevel = "Medium",
                            EducationStartTime = new DateTime(2023, 9, 14, 7, 40, 9, 51, DateTimeKind.Local).AddTicks(1034),
                            EducationStatus = true,
                            EducationTime = 2,
                            EducationTitle = "TSQL ile Veritabanı programlama eğitimi SQL Server’ın temel dili olan TSQL’i kullanarak veritabanı üzerinde kodlama yapmayı öğretmeyi amaçlamaktadır.",
                            EducationType = "Sınıf",
                            ImageUrl = "tsql.jpg",
                            IsActive = true,
                            Name = "TSQL ile Veri Tabanı Programlama",
                            Price = 0m,
                            Url = "tsql-ile-veritabani-programlama"
                        });
                });

            modelBuilder.Entity("BrightAcademyApp.Entity.Concrete.CourseCategory", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CourseCategories");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            CourseId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            CourseId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            CourseId = 4,
                            CategoryId = 2
                        },
                        new
                        {
                            CourseId = 5,
                            CategoryId = 2
                        },
                        new
                        {
                            CourseId = 6,
                            CategoryId = 3
                        },
                        new
                        {
                            CourseId = 7,
                            CategoryId = 4
                        },
                        new
                        {
                            CourseId = 8,
                            CategoryId = 5
                        },
                        new
                        {
                            CourseId = 9,
                            CategoryId = 5
                        },
                        new
                        {
                            CourseId = 2,
                            CategoryId = 6
                        },
                        new
                        {
                            CourseId = 3,
                            CategoryId = 6
                        });
                });

            modelBuilder.Entity("BrightAcademyApp.Entity.Concrete.CourseTrainee", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TraineeId")
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId", "TraineeId");

                    b.HasIndex("TraineeId");

                    b.ToTable("CourseTrainees");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            TraineeId = "1"
                        },
                        new
                        {
                            CourseId = 1,
                            TraineeId = "2"
                        },
                        new
                        {
                            CourseId = 1,
                            TraineeId = "3"
                        },
                        new
                        {
                            CourseId = 1,
                            TraineeId = "4"
                        },
                        new
                        {
                            CourseId = 2,
                            TraineeId = "1"
                        },
                        new
                        {
                            CourseId = 2,
                            TraineeId = "3"
                        },
                        new
                        {
                            CourseId = 3,
                            TraineeId = "2"
                        },
                        new
                        {
                            CourseId = 3,
                            TraineeId = "4"
                        },
                        new
                        {
                            CourseId = 4,
                            TraineeId = "1"
                        },
                        new
                        {
                            CourseId = 2,
                            TraineeId = "4"
                        },
                        new
                        {
                            CourseId = 5,
                            TraineeId = "3"
                        },
                        new
                        {
                            CourseId = 6,
                            TraineeId = "3"
                        },
                        new
                        {
                            CourseId = 7,
                            TraineeId = "3"
                        });
                });

            modelBuilder.Entity("BrightAcademyApp.Entity.Concrete.CourseTrainer", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrainerId")
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId", "TrainerId");

                    b.HasIndex("TrainerId");

                    b.ToTable("CourseTrainers");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            TrainerId = "5"
                        },
                        new
                        {
                            CourseId = 2,
                            TrainerId = "6"
                        },
                        new
                        {
                            CourseId = 3,
                            TrainerId = "5"
                        },
                        new
                        {
                            CourseId = 4,
                            TrainerId = "6"
                        },
                        new
                        {
                            CourseId = 5,
                            TrainerId = "6"
                        },
                        new
                        {
                            CourseId = 5,
                            TrainerId = "5"
                        },
                        new
                        {
                            CourseId = 6,
                            TrainerId = "6"
                        },
                        new
                        {
                            CourseId = 7,
                            TrainerId = "5"
                        });
                });

            modelBuilder.Entity("BrightAcademyApp.Entity.Concrete.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .HasColumnType("TEXT");

                    b.Property<string>("Questions")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Akademi Merkezi",
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CompanyName = "Bright Academy",
                            Contact = "info@brightacademy.com",
                            Questions = "Sık Sorulan Sorular"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "b69e6273-31f7-417d-a2ab-08c3a1b4adaf",
                            RoleId = "75606044-e0da-4df7-8e91-9ea41d31fe16"
                        },
                        new
                        {
                            UserId = "ebddca1e-a6ac-4af1-8cdc-175a534457de",
                            RoleId = "5d0ac846-22b0-43cf-8b5d-6b9d3f6b01b4"
                        },
                        new
                        {
                            UserId = "1",
                            RoleId = "154e8035-0610-4840-9309-1c9d19e5c19e"
                        },
                        new
                        {
                            UserId = "2",
                            RoleId = "154e8035-0610-4840-9309-1c9d19e5c19e"
                        },
                        new
                        {
                            UserId = "3",
                            RoleId = "154e8035-0610-4840-9309-1c9d19e5c19e"
                        },
                        new
                        {
                            UserId = "4",
                            RoleId = "154e8035-0610-4840-9309-1c9d19e5c19e"
                        },
                        new
                        {
                            UserId = "5",
                            RoleId = "1cee760b-1b69-4d6b-8140-ac5149448a07"
                        },
                        new
                        {
                            UserId = "6",
                            RoleId = "1cee760b-1b69-4d6b-8140-ac5149448a07"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BrightAcademyApp.Entity.Concrete.Role", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Role");

                    b.HasData(
                        new
                        {
                            Id = "75606044-e0da-4df7-8e91-9ea41d31fe16",
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            Description = "Admin Rolü"
                        },
                        new
                        {
                            Id = "5d0ac846-22b0-43cf-8b5d-6b9d3f6b01b4",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN",
                            Description = "Super Admin Rolü"
                        },
                        new
                        {
                            Id = "1cee760b-1b69-4d6b-8140-ac5149448a07",
                            Name = "Trainer",
                            NormalizedName = "TRANIER",
                            Description = "Trainer Rolü"
                        },
                        new
                        {
                            Id = "154e8035-0610-4840-9309-1c9d19e5c19e",
                            Name = "Traniee",
                            NormalizedName = "TRANIEE",
                            Description = "Traniee Rolü"
                        });
                });

            modelBuilder.Entity("BrightAcademyApp.Entity.Concrete.Trainee", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Education")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.ToTable("AspNetUsers", t =>
                        {
                            t.Property("Address")
                                .HasColumnName("Trainee_Address");

                            t.Property("City")
                                .HasColumnName("Trainee_City");

                            t.Property("DateOfBirth")
                                .HasColumnName("Trainee_DateOfBirth");

                            t.Property("Education")
                                .HasColumnName("Trainee_Education");

                            t.Property("FirstName")
                                .HasColumnName("Trainee_FirstName");

                            t.Property("Gender")
                                .HasColumnName("Trainee_Gender");

                            t.Property("LastName")
                                .HasColumnName("Trainee_LastName");
                        });

                    b.HasDiscriminator().HasValue("Trainee");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "19f7e53d-3fd9-4094-b5bc-ff6dcd76aa16",
                            Email = "busradursun@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "BUSRADURSUN@GMAIL.COM",
                            NormalizedUserName = "BUSRADURSUN",
                            PasswordHash = "AQAAAAIAAYagAAAAEMT2u7OSB341ZdDtPrcbEk4VWCAgrS3ipAy/NJvaT8Qtx7SR7b5Jrd0wb9dbRFBdHw==",
                            PhoneNumber = "+905424597000",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "busradursun",
                            Address = "Paşa Mah.Evren Sk.No:8/4 Şişli/İSTANBUL",
                            City = "İstanbul",
                            DateOfBirth = new DateTime(1994, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "Beykent Üniversitesi Yazılım Mühendisliği",
                            FirstName = "Busra",
                            Gender = "Kadın",
                            LastName = "Dursun"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0d04af61-7ab1-4ebb-8e9a-f7ae05071161",
                            Email = "erdincdursun@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "ERDINCDURSUN@GMAIL.COM",
                            NormalizedUserName = "ERDINCDURSUN",
                            PasswordHash = "AQAAAAIAAYagAAAAEBkOussHNOIzu+3EF7gz2nNLZW3lrHoDYQ/Fz+cq/e4vEPri5TQHHwqnp/sQRSfWGA==",
                            PhoneNumber = "+905424597000",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "erdincdursun",
                            Address = "Paşa Mah.Evren Sk.No:8/4 Şişli/İSTANBUL",
                            City = "İstanbul",
                            DateOfBirth = new DateTime(1993, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "Anadolu Üniversitesi Bilgisayar Mühendisliği",
                            FirstName = "Erdinc",
                            Gender = "Erkek",
                            LastName = "Dursun"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fd046d4f-5b61-4b69-9ea9-5748f9a4a367",
                            Email = "seydanur@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "SEYDANUR@GMAIL.COM",
                            NormalizedUserName = "SEYDANUR",
                            PhoneNumber = "+905424597000",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "seydanur",
                            Address = "Talatpaşa Mah.Kiraz Sk.No:8/3 Şişli/İSTANBUL",
                            City = "İstanbul",
                            DateOfBirth = new DateTime(1990, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "Anadolu Üniversitesi Yazılım Mühendisliği",
                            FirstName = "Şeyda Nur",
                            Gender = "Kadın",
                            LastName = "Doğan"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8fc1a511-5902-4081-89ce-b401a4e552f1",
                            Email = "habibedursun@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "HABIBEDURSUN@GMAIL.COM",
                            NormalizedUserName = "HABIBEDURSUN",
                            PhoneNumber = "+905424597000",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "habibedursun",
                            Address = "Yayla Mah.Bakır Sk.No:9/2 Şişli/İSTANBUL",
                            City = "İstanbul",
                            DateOfBirth = new DateTime(1968, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "Anadolu Üniversitesi Bilgisayar Programcılığı",
                            FirstName = "Habibe",
                            Gender = "Kadın",
                            LastName = "Dursun"
                        });
                });

            modelBuilder.Entity("BrightAcademyApp.Entity.Concrete.Trainer", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Education")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstructorExperience")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstructorPoints")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.ToTable("AspNetUsers", t =>
                        {
                            t.Property("FirstName")
                                .HasColumnName("Trainer_FirstName");

                            t.Property("Gender")
                                .HasColumnName("Trainer_Gender");

                            t.Property("LastName")
                                .HasColumnName("Trainer_LastName");
                        });

                    b.HasDiscriminator().HasValue("Trainer");

                    b.HasData(
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "14360811-ff05-40c2-8cd7-d68223ee61f4",
                            Email = "arzuozturk@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "ARZUOZTURK@GMAIL.COM",
                            NormalizedUserName = "ARZUOZTURK",
                            PasswordHash = "AQAAAAIAAYagAAAAEC0i7/l1SvOAI1xO+csb6O+JEy0CY0fqOXIsArE08slz1XtFXZHkVtW1k872nfv7Xw==",
                            PhoneNumber = "+905424597000",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "arzuozturk",
                            Address = "Vakfıkebir Mah.Kamaliye Sk.No:8/4 Trabzon",
                            Branch = "Bilgisayar Öğretmeni",
                            City = "Trabzon",
                            DateOfBirth = new DateTime(1972, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "Marmara Üniversitesi Bilgisayar Öğretmenliği",
                            FirstName = "Arzu",
                            Gender = "Kadın",
                            InstructorExperience = "Özel okul Bilgisayar Öğretmeliği",
                            InstructorPoints = 5,
                            IsActive = true,
                            LastName = "Öztürk"
                        },
                        new
                        {
                            Id = "6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5ce96608-6dd8-4415-b297-763176ac20ed",
                            Email = "nazlıozturk@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "NAZLIOZTURK@GMAIL.COM",
                            NormalizedUserName = "NAZLIOZTURK",
                            PasswordHash = "AQAAAAIAAYagAAAAEFu8YJaxS0EmWpMJQeqdSe53o3G+nPr/KajDnqfVrLxcMhHHY03+RzH+i+eeP17jJg==",
                            PhoneNumber = "+905424597000",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "nazliozturk",
                            Address = "Vakfıkebir Mah.Kamaliye Sk.No:8/4 Trabzon",
                            Branch = "Bilgisayar Öğretmeni",
                            City = "Trabzon",
                            DateOfBirth = new DateTime(2004, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "Aydın Üniversitesi Bilgisayar Öğretmenliği",
                            FirstName = "Nazlı",
                            Gender = "Kadın",
                            InstructorExperience = "Bilge adam Yazılım Eğitmenliği",
                            InstructorPoints = 5,
                            IsActive = true,
                            LastName = "Öztürk"
                        });
                });

            modelBuilder.Entity("BrightAcademyApp.Entity.Concrete.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = "b69e6273-31f7-417d-a2ab-08c3a1b4adaf",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "83e4853d-bb95-4ad1-9863-09bc8ff5b3ed",
                            Email = "omerayaz@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "OMERAYAZ@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAENfg0a+4lp90jeEzIUxr6U7Frxi7iYL3gqtxGVJh9FeNJj3IsWSJMJt+BOc9fyQl+Q==",
                            PhoneNumber = "+905424597000",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin",
                            FirstName = "Ömer Ayaz",
                            Gender = "Erkek",
                            LastName = "Dursun"
                        },
                        new
                        {
                            Id = "ebddca1e-a6ac-4af1-8cdc-175a534457de",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c1d9598c-fb8a-4a47-98ca-6eed41451707",
                            Email = "aysehafsa@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "AYSEHAFSA@GMAIL.COM",
                            NormalizedUserName = "SUPERADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEEor/fADQibZJZoWk87lwrJLkY3OtN5kP6VxUVnDho37tmLVpn0jt0VbZqfjPBTl6Q==",
                            PhoneNumber = "+905424597000",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "superadmin",
                            FirstName = "Ayse Hafsa",
                            Gender = "Kadın",
                            LastName = "Dogan"
                        });
                });

            modelBuilder.Entity("BrightAcademyApp.Entity.Concrete.CourseCategory", b =>
                {
                    b.HasOne("BrightAcademyApp.Entity.Concrete.Category", "Category")
                        .WithMany("CourseCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrightAcademyApp.Entity.Concrete.Course", "Course")
                        .WithMany("CourseCategories")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("BrightAcademyApp.Entity.Concrete.CourseTrainee", b =>
                {
                    b.HasOne("BrightAcademyApp.Entity.Concrete.Course", "Course")
                        .WithMany("CourseTraniees")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrightAcademyApp.Entity.Concrete.Trainee", "Trainee")
                        .WithMany("CourseTraniees")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("BrightAcademyApp.Entity.Concrete.CourseTrainer", b =>
                {
                    b.HasOne("BrightAcademyApp.Entity.Concrete.Course", "Course")
                        .WithMany("CourseTraniners")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrightAcademyApp.Entity.Concrete.Trainer", "Trainer")
                        .WithMany("CourseTraniners")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BrightAcademyApp.Entity.Concrete.Category", b =>
                {
                    b.Navigation("CourseCategories");
                });

            modelBuilder.Entity("BrightAcademyApp.Entity.Concrete.Course", b =>
                {
                    b.Navigation("CourseCategories");

                    b.Navigation("CourseTraniees");

                    b.Navigation("CourseTraniners");
                });

            modelBuilder.Entity("BrightAcademyApp.Entity.Concrete.Trainee", b =>
                {
                    b.Navigation("CourseTraniees");
                });

            modelBuilder.Entity("BrightAcademyApp.Entity.Concrete.Trainer", b =>
                {
                    b.Navigation("CourseTraniners");
                });
#pragma warning restore 612, 618
        }
    }
}
